apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-auth
spec:
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
        - name: backend-auth
          image: veetik/ecommerce-project-b-auth:latest
          ports:
          - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-auth
spec:
  selector:
    app: backend-auth
  ports: 
    - protocol: TCP
      port: 80  
      targetPort: 3000
      name: http

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-ugc
spec:
  selector:
    matchLabels:
      app: backend-ugc
  template:
    metadata:
      labels:
        app: backend-ugc
    spec:
      containers:
        - name: backend-ugc
          image: veetik/ecommerce-project-b-ugc:latest
          ports:
          - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ugc
spec:
  selector:
    app: backend-ugc
  ports: 
    - protocol: TCP
      port: 80  
      targetPort: 3000
      name: http

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-catalogue
spec:
  selector:
    matchLabels:
      app: backend-catalogue
  template:
    metadata:
      labels:
        app: backend-catalogue
    spec:
      containers:
        - name: backend-catalogue
          image: veetik/ecommerce-project-b-catalogue:latest
          ports:
          - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-catalogue
spec:
  selector:
    app: backend-catalogue
  ports: 
    - protocol: TCP
      port: 80  
      targetPort: 3000
      name: http

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-search
spec:
  selector:
    matchLabels:
      app: backend-search
  template:
    metadata:
      labels:
        app: backend-search
    spec:
      containers:
        - name: backend-search
          image: veetik/ecommerce-project-b-search:latest
          ports:
          - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-search
spec:
  selector:
    app: backend-search
  ports: 
    - protocol: TCP
      port: 80  
      targetPort: 3000
      name: http