version: '3.9'

services:
  test-zinc: 
    image: public.ecr.aws/h9e2j3o7/zinc
    env_file:
      - .env.test
    volumes:
      - ./TEST-DATA/zinc:/data

  test-users-db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    restart: unless-stopped

  test-catalogue-db:
    image: postgres
    env_file:
      - .env.test
    restart: unless-stopped

  test-ugc-db:
    image: postgres
    env_file:
      - .env.test
    restart: unless-stopped

  test-users-api:
    depends_on:
      - test-users-db
    env_file:
      - .env.test
    image: veetik/ecommerce-project-b-users:test
    restart: unless-stopped

  test-auth-api:
    depends_on:
      - test-users-db
    env_file:
      - .env.test
    image: veetik/ecommerce-project-b-auth:test
    restart: unless-stopped
  
  test-catalogue-api:
    depends_on:
      - test-catalogue-db
    env_file:
      - .env.test
    image: veetik/ecommerce-project-b-catalogue:test
    restart: unless-stopped

  test-ugc-api:
    depends_on:
      - test-ugc-db
    env_file:
      - .env.test
    image: veetik/ecommerce-project-b-ugc:test
    restart: unless-stopped

  test-search-api:
    depends_on:
      - test-zinc
    env_file:
      - .env.test
    image: veetik/ecommerce-project-b-search:test
    restart: unless-stopped

  test-runner:
    depends_on:
      - test-auth-api
      - test-users-api
      - test-catalogue-api
      - test-ugc-api
      - test-search-api
    env_file:
      - .env.test
    image: veetik/ecommerce-project-b-integration-tests:latest