version: "3.9"

services:
  test-db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./TEST-DATA/db:/var/lib/postgresql/data
    # logging: 
    #   driver: none

  test-zinc:
    image: public.ecr.aws/prabhat/zinc
    depends_on:
      - test-db
    environment:
      - DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=test
      - ZINC_FIRST_ADMIN_PASSWORD=test
    volumes:
      - ./TEST-DATA/zinc:/data
    logging: 
      driver: none

  test-backend: 
    image: test-backend
    depends_on:
      - test-db
      - test-zinc
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.test
    environment:
      - DATABASE_URL=postgres://test:test@test-db:5432/test
    command: dockerize -wait tcp://test-db:5432 -timeout 30s sh -c "yarn prisma db push && yarn prisma db seed && yarn dev"
    # logging: 
    #   driver: none

  test-runner: 
    image: test-backend
    depends_on:
      - test-db
      - test-zinc
      - test-backend
    environment:
      - DATABASE_URL=postgres://test:test@test-db:5432/test
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.test
    command: dockerize -wait tcp://test-db:5432 -wait tcp://test-backend:3000 -timeout 30s sh -c "yarn test"