version: "3.9"

services:
  dev-db:
    image: postgres
    ports:
      - "35801:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    restart: unless-stopped
    volumes:
      - dev-db:/var/lib/postgresql/data

  dev-loadbalancer:
    depends_on:
      - dev-db
    image: nginx
    ports:
      - "4000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dev-db:
