version: '3.9'

services:
  test-zinc: 
    image: public.ecr.aws/h9e2j3o7/zinc
    ports:
      - "36800:4080"
    environment:
      - DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=test
      - ZINC_FIRST_ADMIN_PASSWORD=test
    volumes:
      - ./TEST-DATA/zinc:/data
    
  test-users-db:
    image: postgres
    ports:
      - "36801:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    restart: unless-stopped

  test-catalogue-db:
    image: postgres
    ports:
      - "36802:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    restart: unless-stopped

  test-loadbalancer: 
    depends_on:
      - test-users-db
      - test-catalogue-db
    image: nginx
    ports: 
      - "80:5000"
    volumes:
      - ./nginx.test.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"