apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-backend-config
data:
  SERVICE_AUTH_URL: 'http://localhost:3001'
  SERVICE_AUTH_PORT: '3001'
  SERVICE_CATALOGUE_URL: 'http://localhost:3002'
  SERVICE_CATALOGUE_PORT: '3002'
  NODE_ENV: 'production'
  DATABASE_URL: 'mysql://u6xzueyvt5i1:pscale_pw_5rdFNeWBGWNS9QcSIg2Dnw10zxbrPz-RtYFfiSbMQio@vuki6w2b4qoh.eu-west-3.psdb.cloud/test?sslaccept=strict'