name: 'Backend-auth: build Docker image'

on: 
  push:
    paths: 
      - 'backend/apps/auth'
      - 'backend/packages/**'
    branches:   
      - master
  workflow_dispatch:

jobs:
  build-code: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 17.8.0
      uses: actions/setup-node@v3
      with:
        node-version: '17.8.0'

    - name: Build code
      run: yarn build:backend

  build-image: 
    needs: build-code
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:backend"
          build-args: [SCOPE=backend-auth]
          push: true
          tags: veetik/ecommerce-project-b-auth:latest