name: 'Backend: build code and run tests'

on: 
  push:
    paths: 
      - 'backend/**'
    branches:   
      - master
  pull_request:
    paths: 
      - 'backend/**'
    branches:   
      - master
    
jobs:
  build: 
    runs-on: ubuntu-latest
    name: "Backend: build code and run tests"

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 17.8.0
      uses: actions/setup-node@v3
      with:
        node-version: '17.8.0'

    - name: Build
      run: yarn build:backend
    
    - name: Test
      run: yarn test:backend