name: 'Backend: build code'

on: 
  push:
    # paths: 
    #   - 'backend/**'
    branches:   
      - master

jobs:
  # build-code:     
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Use Node.js 17.8.0
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '17.8.0'

  #   - name: Build code
  #     run: yarn build:backend
  
  docker-stuff:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"

    - name: Determine builds
      id: builds
      run: |
        for i in ${{ steps.getfile.outputs.files }}
        do
          if [[ "backend/apps/auth" == *$i* ]]; then
            echo "::set-output name=auth::'true'"
          elif [[ "backend/" == *$i* ]]; then
            echo "::set-output name=test::'true'"
          fi
        done
    
    - name: test
      if: ${{ steps.builds.outputs.test == 'true' }}
      run: echo "test"

